SHELL:=/bin/bash
#KERNEL=add
#KERNEL_TOP=VecAdd
#KERNEL_ARGS=
PLATFORM=xilinx_u280_gen3x16_xdma_1_202211_1
BUILD_DIR_PREFIX=${SIM_WS}/builds/sb/vadd-hbstream-nestedbuffer/
# BUILD_DIR_PREFIX=builds

#XRT_INI_PATH=scripts/xrt.ini
MAX_SYNTH_JOBS=24
#STRATEGY="Explore"
#PLACEMENT_STRATEGY="EarlyBlockPlacement"

include ../common.mk
