#!/bin/bash

##----------
## Conda Installation
##----------
CONDA_PATH=$(which conda)
if [[ $CONDA_PATH == "" ]]; then
	echo "ERROR: Conda isn't installed."
	exit
fi
if [[ $CONDA_PREFIX == "" ]]; then
	echo "ERROR: Looks like Conda environment isn't loaded."
	exit
fi

conda install -y -c anaconda cmake python=3.9
INSTALL_PREFIX=$CONDA_PREFIX
PROJECT_DIR=$(dirname $PWD)

##----------
## PASTA
##----------
cd $PROJECT_DIR
#git checkout docs
cd tapa
TAPA_DIR=$PWD
cd backend/python
if [[ -d build ]]; then
	echo "ERROR: A build folder already exists."
	echo "If you wish to reinstall, delete the existing build with:"
	echo "rm -rf $TAPA_DIR/backend/python/build"
	exit
fi
# install the tapa package to a custom build directory
# --verbose	: idk... just helpful
# --force	: there might be a previous installation, overwrite that
# --system	: required because of a faulty Ubuntu patch: https://github.com/pypa/pip/issues/3826
# --target	: this is the directory that will ultimately be linked
mkdir build && pip3 install --verbose --force --target build/ .
if [ $? -eq 0 ]
then
  echo "Built TAPA backend"
else
  echo "Could not build TAPA backend!" >&2
  exit
fi

echo "INFO: Installed TAPAC backend"

# Build tapac
cd $TAPA_DIR
if [[ -d build ]]; then
	echo "ERROR: A build folder already exists."
	echo "If you wish to reinstall, delete the existing build with:"
	echo "rm -rf $TAPA_DIR/build"
	exit
fi
mkdir build && cd build
cmake ..
# Launch the build on limited procs, based on avg load of the last 5 minutes.
# This might accelerate single runs, but is super bad for batch jobs.
AVG_LOAD=$(cat /proc/loadavg | awk '{print $2; }')
AVG_LOAD=${AVG_LOAD%.*}
# but leave 4 procs for sanity
JOBS=$(($(nproc --all)-$AVG_LOAD-4))
echo "Launching CMake with $JOBS jobs"
make -j $JOBS

# Check status
if [ $? -eq 0 ]
then
  echo "Built TAPA"
else
  echo "Could not build TAPA!" >&2
  exit
fi

#----------
# Install in environment
#----------
echo "Linking install..."
sudo mkdir -p $INSTALL_PREFIX/bin
sudo mkdir -p $INSTALL_PREFIX/include
sudo mkdir -p $INSTALL_PREFIX/lib
sudo ln -sfn "${PWD}"/backend/tapacc $INSTALL_PREFIX/bin/
sudo ln -sfn "${PWD}"/../src/tapa $INSTALL_PREFIX/include/
sudo ln -sfn "${PWD}"/../src/tapa.h $INSTALL_PREFIX/include/
sudo ln -sfn "${PWD}"/libtapa.a $INSTALL_PREFIX/lib/
sudo ln -sfn "${PWD}"/libtapa.so $INSTALL_PREFIX/lib/

cd $PROJECT_DIR
touch setup
echo "#!/bin/bash" > setup
echo "export PROJECT_DIR=$PROJECT_DIR" >> setup
echo "conda activate $(basename $INSTALL_PREFIX)" >> setup
cat installer/setenv >> setup

echo -en "Done!\n\nAfter navigating to the project directory $PROJECT_DIR, use \`source setup\` to load the environment.\n"


